name: Features

on:
  push:
    branches:
      - features/*

env:
  DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
  DEPLOY_USER: ${{ vars.DEPLOY_USER }}
  DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x', '18.x', '16.x']

    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          node --version
          npm --version
          npm ci

      - name: Run Lint
        run: npm run lint
