name: Tests

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
  DEPLOY_USER: ${{ vars.DEPLOY_USER }}
  DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

jobs:
  test_old_versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.x', '16.x']

    steps:
      - uses: actions/checkout@v3

      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          node --version
          npm --version
          npm ci

      - name: Run Tests
        run: ./bin/tests.sh

  test_and_deploy_latest_lts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: SSH Key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          ls -la ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ls -la ~/.ssh/

      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: |
          node --version
          npm --version
          npm ci

      - name: Run Tests
        run: ./bin/tests.sh

      - name: Deploy
        run: ./bin/deploy.sh
